// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Everything under .starlightdown/ is regenerated by starlightdown::build_site().
// This file is yours: edit it to add integrations or override anything below.
import sd from './.starlightdown/config.mjs';

export default defineConfig({
	site: sd.site,
	base: sd.base,
	integrations: [starlight({ ...sd.starlight })],
});
