# The machine-owned directory ------------------------------------------------
#
# `starlight/.starlightdown/` is regenerated on every build and on scaffold.
# Nothing a user edits lives here: the vendored plugin, the manifest, the
# generated Astro config and a version stamp. Everything outside it --
# astro.config.mjs, ec.config.mjs, src/styles/custom.css, package.json -- is
# written once and then left alone.

#' @noRd
sd_machine_dir <- function(site_path) fs::path(site_path, ".starlightdown")

#' Create or refresh `.starlightdown/`
#'
#' @param site_path The Starlight project directory.
#' @return Invisibly, the path to the machine directory.
#' @noRd
sd_sync_machine_dir <- function(site_path, theme = "default") {
  machine <- sd_machine_dir(site_path)
  fs::dir_create(machine)

  sd_sync_plugin(machine)
  sd_write_astro_config(machine, theme)
  sd_write_file(
    paste0(as.character(utils::packageVersion("starlightdown")), "\n"),
    fs::path(machine, "template-version")
  )

  invisible(as.character(machine))
}

# The plugin is vendored rather than published: npm resolves it through a
# `file:` dependency, and npm symlinks such a dependency, so refreshing the
# copy takes effect without reinstalling.
#' @noRd
sd_sync_plugin <- function(machine) {
  source_dir <- system.file("starlight-plugin", package = "starlightdown")
  if (!nzchar(source_dir) || !fs::dir_exists(source_dir)) {
    cli::cli_abort("The bundled Starlight plugin is missing from the installed package.")
  }

  target <- fs::path(machine, "plugin")
  unlink(target, recursive = TRUE)
  fs::dir_copy(source_dir, target)

  sd_stamp_plugin_version(fs::path(target, "package.json"))
  invisible(as.character(target))
}

# Edited through jsonlite rather than by rewriting text, so the file stays
# valid JSON no matter what it contained.
#' @noRd
sd_stamp_plugin_version <- function(path) {
  if (!fs::file_exists(path)) {
    return(invisible(NULL))
  }
  manifest <- jsonlite::read_json(path)
  manifest$version <- as.character(utils::packageVersion("starlightdown"))
  sd_write_file(
    paste0(jsonlite::toJSON(manifest, auto_unbox = TRUE, pretty = TRUE), "\n"),
    path
  )
  invisible(path)
}

#' Write `.starlightdown/config.mjs`
#'
#' Generated verbatim in the shape CONTRACT.md §3 specifies. It reads
#' `site.json` with `readFileSync` rather than a JSON import assertion, which
#' needs no Node flags and no `with { type: 'json' }` support in the Astro
#' config loader.
#' @noRd
sd_write_astro_config <- function(machine, theme = "default") {
  version <- as.character(utils::packageVersion("starlightdown"))
  preset <- sd_theme_presets[[theme]]

  # Starlight applies plugins in array order, and a preset registered after
  # starlightdown overwrites the same override slots outright. Registered
  # before, it is picked up and wrapped instead (CONTRACT.md \u00a711).
  plugin_line <- if (is.null(preset)) {
    "\tplugins: [starlightdown({ manifest, theme: manifest.site.theme })],"
  } else {
    paste0(
      "\tplugins: [", preset$import,
      "(), starlightdown({ manifest, theme: manifest.site.theme })],"
    )
  }
  plugin_comment <- if (is.null(preset)) {
    character()
  } else {
    c(
      "\t// The theme preset must come first: starlightdown claims the same override",
      "\t// slots and renders whatever it finds there inside its own markup."
    )
  }
  preset_import <- if (is.null(preset)) {
    character()
  } else {
    paste0("import ", preset$import, " from '", preset$package, "';")
  }

  lines <- c(
    paste0("// Generated by starlightdown ", version, ". Do not edit \u2014 rewritten on every build."),
    "// Edit ../astro.config.mjs or ../src/styles/custom.css instead.",
    "",
    "import { readFileSync } from 'node:fs';",
    preset_import,
    "import starlightdown from 'starlightdown-starlight';",
    "",
    "const manifest = JSON.parse(readFileSync(new URL('./site.json', import.meta.url), 'utf8'));",
    "",
    "const social = [];",
    "if (manifest.package.urls.repo?.includes('github.com')) {",
    "\tsocial.push({ icon: 'github', label: 'GitHub', href: manifest.package.urls.repo });",
    "}",
    "",
    "// Astro wants a string or nothing; a null would arrive as an object.",
    "export const site = manifest.site.url ?? undefined;",
    "export const base = manifest.site.base;",
    "",
    "export const starlight = {",
    "\ttitle: manifest.package.title,",
    "\tdescription: manifest.package.description,",
    "\tfavicon: '/favicon.svg',",
    "\tsocial,",
    "\tsidebar: manifest.sidebar,",
    "\tlastUpdated: false,",
    "\t// Loaded after the theme, so user rules win.",
    "\tcustomCss: ['./src/styles/custom.css'],",
    plugin_comment,
    plugin_line,
    "};",
    "",
    "export default { site, base, starlight, manifest };"
  )
  sd_write_file(paste0(paste0(lines, collapse = "\n"), "\n"), fs::path(machine, "config.mjs"))
}

#' Manifest path inside the machine directory
#' @noRd
sd_manifest_path <- function(site_path) fs::path(sd_machine_dir(site_path), "site.json")
